server:
  port: 8084
  # tomcat的https地址问题, 加这个可以直接获得https的url
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
# 日志配置
logging:
  file: ./log/service.log
  level:
    com.hyhcoder: debug
    org.springframework.boot.autoconfigure: ERROR
# spring常规配置
spring:
  # 数据库及连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.128:3306/quickframe?useUnicode=true&useSSL=false
    username: root
    password: 123456
    druid:
      # 初始化连接数
      initial-size: 5
      # 最大活跃连接数
      max-active: 20
      # 最小保持连接数
      min-idle: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  # redis配置
  redis:
    host: 192.168.40.128
    port: 6379
    password: 123456
mybatis:
  mapper-locations: classpath*:/mapper/*.xml


